const moviesData = [
  {
    id: Math.random(),
    image: "https://resizing.flixster.com/rR0bwcBod-5ADgdtVXYfHLTVj54=/ems.ZW1zLXByZC1hc3NldHMvbW92aWVzLzRkMjQ4MDUwLTk1ODQtNDBjOC1hNGNlLTQ5MWQxZGY0YWYyNS53ZWJw",
    rating: 5,
    name: "FREE GUY",
    date: "May 21, 2021",
    runTime : "",
    genre : "Comedy, Action",
    overview: "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
  },
  {
    id: Math.random(),
    image: "https://upload.wikimedia.org/wikipedia/en/4/40/Hillbilly_Elegy_%28film%29.png",
    rating: 5,
    name: "HILLBILLY ELEGY",
    date: "Nov 24, 2020",
    runTime : "1h 56m",
    genre : "Drama",
    overview: "A Yale Law student drawn back to his Appalachian hometown reflects on his family's history and his own future.",
  },
  {
    id: Math.random(),
    image: "https://fr.web.img4.acsta.net/c_310_420/pictures/20/10/29/08/13/5059182.jpg",
    rating: 5,
    name: "ZAPPA",
    date: "Nov 27, 2020",
    runTime : "2h 9m",
    genre : "Documentary, Music",
    overview: "With unfettered access to the Zappa family trust and all archival footage, ZAPPA explores the private life behind the mammoth musical career that never shied away from the political turbulence of its time. Alex Winter’s assembly features appearances by Frank’s widow Gail Zappa and several of Frank’s musical collaborators including Mike Keneally, Ian Underwood, Steve Vai, Pamela Des Barres, Bunk Gardner, David Harrington, Scott Thunes, Ruth Underwood, Ray White and others.",
  },
  {
    id: Math.random(),
    image: "https://resizing.flixster.com/TXVDdZBgP68eoSfNKVDzSxh7eYk=/206x305/v2/https://resizing.flixster.com/867MPHLo3khx6TYB8IetaEWYnD4=/ems.ZW1zLXByZC1hc3NldHMvbW92aWVzL2NmYzVlYjE2LWE4YWUtNGVhNy05NzhjLTkxOTgzMjc4NjcyYi5qcGc=",
    rating: 5,
    name: "EMBATTLED",
    date: "Nov 20, 2020",
    runTime : "1h 57m",
    genre : "Drama",
    overview: "The eldest son of a ruthlessly tough MMA champion must fight his way out of the abusive cycle his father has continued.",
  },
  {
    id: Math.random(),
    image: "https://img5.cdn.cinoche.com/images/41666fc9d722224eb2c57a2128c4b6f6.jpg",
    rating: 5,
    name: "FATALE",
    date: "Dec 18, 2020",
    runTime : " 1h 43m",
    genre : "Mystery And Thriller",
    overview: "After a wild one-night stand, Derrick (Michael Ealy), a successful sports agent, watches his perfect life slowly disappear when he discovers that the sexy and mysterious woman he risked everything for, is a determined police detective (Hilary Swank) who entangles him in her latest investigation. As he tries desperately to put the pieces together, he falls deeper into her trap, risking his family, his career, and even his life. FATALE is a suspenseful and provocative psychological thriller and an unpredictable game of cat and mouse where one mistake can change your life.",
  },
  {
    id: Math.random(),
    image: "https://fr.web.img6.acsta.net/pictures/20/09/16/09/31/0119617.jpg",
    rating: 5,
    name: "THE FATHER",
    date: "Feb 26, 2021",
    runTime : "1h 37m",
    genre : "Drama",
    overview: "",
  },
  {
    id: Math.random(),
    image: "https://www.bifff.net/wp-content/uploads/2020/03/BREAKING-SURFACE_Poster_BIFFF2020.jpg",
    rating: 5,
    name: "BREAKING SURFACE",
    date: "Dec 15, 2020",
    runTime : "1h 35m",
    genre : "Drama, Action",
    overview: "A few days after Christmas, half-sisters Ida and Tuva set out on a winter dive in a remote part of the Norwegian coastline. Towards the end of the dive, a rockslide traps Tuva under water. As Ida surfaces to call for help, she discovers that the rockslide has struck above water as well, burying their equipment, phones and car keys--they are completely cut off from any chance of outside rescue. As the frantic race for survival unfolds, Ida is put to the ultimate test of character and forcefulness. During Ida's fight to save Tuva, a fractured sisterhood is exposed, and when all seems lost, the stakes rise beyond simple survival.",
  },
  {
    id: Math.random(),
    image : "https://resizing.flixster.com/-9KGuKSefZNnqvRYiz0paY_AKtU=/206x305/v2/https://resizing.flixster.com/HSmRh_QnVZ8MlwEmKBtu29HbAk4=/ems.ZW1zLXByZC1hc3NldHMvbW92aWVzL2UxODE0M2NiLWMzMzQtNGZjMi1hMGVjLTM4NTIzZTQyNzFmYi5qcGc=",
    rating: 5,
    name: "SAFETY",
    date: "Dec 11, 2020",
    runTime : "2h 2m",
    genre : "Biography, Drama",
    overview: "Safety is a drama inspired by the empowering story of former Clemson University football safety Ray McElrathbey (Jay Reeves), a young man facing a series of challenging circumstances, whose dedication and persistence help him to triumph over repeated adversities. Aided by his teammates and the Clemson community, he succeeds on the field while simultaneously raising and caring for his 11-year-old brother Fahmarr (Thaddeus J. Mixson).",
  },

];

  export default moviesData;